version: '2'
services:
  user-nginx:
    image: user-nginx
    build: docker/nginx/
    volumes:
      - .:/var/www/
  user-php:
    image: user-php
    build: docker/php/
    working_dir: /var/www/
    volumes:
      - .:/var/www/
  arangodb:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=root
