openapi: 3.0.0
info:
  title: user service api
  description: Api for user management and authentication
  version: '0.0.1'
servers:
- url: https://127.0.0.1:8443/
  description: 'Development docker-compose'
tags:
- name: user
  description: Operations directly related to users
- name: authentication
  description: Everything related to authentication
paths:
  /user:
    post:
      tags:
      - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/{user-id}:
    get:
      tags:
      - user
      parameters:
      - $ref: '#/components/parameters/user-id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - user
      parameters:
      - $ref: '#/components/parameters/user-id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - user
      parameters:
      - $ref: '#/components/parameters/user-id'
      responses:
        200:
          description: OK
  /authentication:
    post:
      tags:
      - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: OK
    delete:
      tags:
      - authentication
      responses:
        200:
          description: OK
  /authentication/{token}:
    get:
      tags:
        - authentication
      parameters:
      - $ref: '#/components/parameters/token'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  parameters:
    user-id:
      in: path
      name: user-id
      description: Id of the user
      required: true
      schema:
        type: string
        example: 45497
    token:
      in: path
      name: token
      description: Identifier token
      required: true
      schema:
        type: string
        example: ag983j49a8jgf9erjg9e485
  schemas:
    Login:
      type: object
      properties:
        user:
          type: string
          example: User123|user123@mail.com
        password:
          $ref: '#/components/schemas/User/properties/password'
    User:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          example: 45497
        user:
          type: string
          example: User123
        email:
          type: string
          example: user123@mail.com
        password:
          type: string
          writeOnly: true
          example: password123
        first-name:
          type: string
          example: Luke
        last-name:
          type: string
          example: Skywalker
        birthday:
          type: string
          example: '1990-12-31'
